"""teste: populando tabelas medicamentos, movimentacoes, lote, usuario, paciente

Revision ID: 2a58588a26d3
Revises: b3bb586a452a
Create Date: 2026-05-18 10:40:26.844544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a58588a26d3'
down_revision: Union[str, Sequence[str], None] = 'b3bb586a452a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=15), nullable=False),
    sa.Column('condicao_clinica', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_paciente_condicao_clinica'), 'paciente', ['condicao_clinica'], unique=False)
    op.add_column('lote', sa.Column('registrado_por', sa.UUID(as_uuid=False), nullable=True))
    op.drop_constraint(op.f('lote_registrado_por_id_fkey'), 'lote', type_='foreignkey')
    op.create_foreign_key(None, 'lote', 'usuario', ['registrado_por'], ['id'], ondelete='SET NULL')
    op.drop_column('lote', 'registrado_por_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lote', sa.Column('registrado_por_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lote', type_='foreignkey')
    op.create_foreign_key(op.f('lote_registrado_por_id_fkey'), 'lote', 'usuario', ['registrado_por_id'], ['id'], ondelete='SET NULL')
    op.drop_column('lote', 'registrado_por')
    op.drop_index(op.f('ix_paciente_condicao_clinica'), table_name='paciente')
    op.drop_table('paciente')
    # ### end Alembic commands ###
