"""teste: adicionando tabelas medicamentos, movimentacoes, lote

Revision ID: 6d0344cbd83c
Revises: 
Create Date: 2026-05-08 14:54:26.541182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0344cbd83c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicamento',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome_generico', sa.String(length=255), nullable=False),
    sa.Column('nome_comercial', sa.String(length=255), nullable=True),
    sa.Column('forma_farmaceutica', sa.String(length=100), nullable=False),
    sa.Column('concentracao', sa.String(length=100), nullable=False),
    sa.Column('via_administracao', sa.String(length=100), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('medicamento_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('registrado_por', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('numero_lote', sa.String(length=100), nullable=False),
    sa.Column('fabricante', sa.String(length=255), nullable=False),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.Column('quantidade_inicial', sa.Integer(), nullable=False),
    sa.Column('quantidade_atual', sa.Integer(), nullable=False),
    sa.Column('entrada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamento.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacao',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lote_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('usuario_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', 'PERDA', 'AJUSTE', name='tipo_movimentacao'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('justificativa', sa.String(length=255), nullable=True),
    sa.Column('ocorrido_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacao')
    op.drop_table('lote')
    op.drop_table('medicamento')
    # ### end Alembic commands ###
