"""incluindo dispensacoes

Revision ID: a575246ce0ba
Revises: c2cf2197c6b3
Create Date: 2026-05-20 17:56:21.169676

Encadeada depois da migration de baseline. Quando foi escrita, as tabelas que
ela pressupõe existirem tinham sido criadas manualmente no Supabase; o baseline
c2cf2197c6b3 passou a criá-las, e esta migration continua a partir dali.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a575246ce0ba'
down_revision: Union[str, Sequence[str], None] = 'c2cf2197c6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispensacao',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('paciente_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('movimentacao_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dispensado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movimentacao_id'], ['movimentacao.id'], name=op.f('dispensacao_movimentacao_id_fkey')),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], name=op.f('dispensacao_paciente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dispensacao_pkey'))
    )
    op.create_index(op.f('ix_alertas_lote_id'), 'alertas', ['lote_id'], unique=False)
    op.create_index(op.f('ix_alertas_medicamento_id'), 'alertas', ['medicamento_id'], unique=False)
    op.create_index(op.f('ix_alertas_status_alerta'), 'alertas', ['status_alerta'], unique=False)
    op.drop_constraint(op.f('alertas_medicamento_id_fkey'), 'alertas', type_='foreignkey')
    op.drop_constraint(op.f('alertas_lote_id_fkey'), 'alertas', type_='foreignkey')
    op.create_foreign_key(op.f('alertas_lote_id_fkey'), 'alertas', 'lote', ['lote_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('alertas_medicamento_id_fkey'), 'alertas', 'medicamento', ['medicamento_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('alertas_medicamento_id_fkey'), 'alertas', type_='foreignkey')
    op.drop_constraint(op.f('alertas_lote_id_fkey'), 'alertas', type_='foreignkey')
    op.create_foreign_key(op.f('alertas_lote_id_fkey'), 'alertas', 'lote', ['lote_id'], ['id'])
    op.create_foreign_key(op.f('alertas_medicamento_id_fkey'), 'alertas', 'medicamento', ['medicamento_id'], ['id'])
    op.drop_index(op.f('ix_alertas_status_alerta'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_medicamento_id'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_lote_id'), table_name='alertas')
    op.drop_table('dispensacao')
    # ### end Alembic commands ###
