"""teste: populando tabelas medicamentos, movimentacoes, lote, usuario

Revision ID: b3bb586a452a
Revises: e61709f10c84
Create Date: 2026-05-13 16:38:14.252670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3bb586a452a'
down_revision: Union[str, Sequence[str], None] = 'e61709f10c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicamento',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome_generico', sa.String(length=255), nullable=False),
    sa.Column('nome_comercial', sa.String(length=255), nullable=True),
    sa.Column('forma_farmaceutica', sa.String(length=100), nullable=False),
    sa.Column('concentracao', sa.String(length=100), nullable=False),
    sa.Column('via_administracao', sa.String(length=100), nullable=False),
    sa.Column('fabricante', sa.String(length=200), nullable=True),
    sa.Column('cod_ggrem', sa.String(length=30), nullable=True),
    sa.Column('registro_anvisa', sa.String(length=30), nullable=True),
    sa.Column('codigo_barras', sa.String(length=30), nullable=True),
    sa.Column('classe_terapeutica', sa.String(length=120), nullable=True),
    sa.Column('tipo_produto', sa.String(length=30), nullable=True),
    sa.Column('tarja', sa.String(length=60), nullable=True),
    sa.Column('restricao_hospitalar', sa.Boolean(), nullable=False),
    sa.Column('indicacao_farmacia_popular', sa.String(length=60), nullable=True),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_ggrem')
    )
    op.create_index(op.f('ix_medicamento_indicacao_farmacia_popular'), 'medicamento', ['indicacao_farmacia_popular'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('ATENDENTE', 'FARMACEUTICO', 'GESTOR', name='perfil_usuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_login'), 'usuario', ['login'], unique=True)
    op.create_table('lote',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('medicamento_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('registrado_por_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('numero_lote', sa.String(length=60), nullable=False),
    sa.Column('fabricante', sa.String(length=200), nullable=True),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.Column('quantidade_inicial', sa.Integer(), nullable=False),
    sa.Column('quantidade_atual', sa.Integer(), nullable=False),
    sa.Column('entrada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamento.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lote_medicamento_id'), 'lote', ['medicamento_id'], unique=False)
    op.create_index(op.f('ix_lote_validade'), 'lote', ['validade'], unique=False)
    op.create_table('movimentacao',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lote_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('usuario_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', 'PERDA', 'AJUSTE', name='tipo_movimentacao'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('justificativa', sa.String(length=255), nullable=True),
    sa.Column('ocorrido_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacao')
    op.drop_index(op.f('ix_lote_validade'), table_name='lote')
    op.drop_index(op.f('ix_lote_medicamento_id'), table_name='lote')
    op.drop_table('lote')
    op.drop_index(op.f('ix_usuario_login'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_medicamento_indicacao_farmacia_popular'), table_name='medicamento')
    op.drop_table('medicamento')
    # ### end Alembic commands ###
