"""baseline: schema inicial completo

Revision ID: c2cf2197c6b3
Revises: 
Create Date: 2026-08-26 18:49:38.198653

Migration de baseline.

As seis primeiras tabelas do sistema (usuario, medicamento, paciente, lote,
movimentacao e alertas) foram criadas manualmente no Supabase, sem passar pelo
Alembic. O resultado é que a migration seguinte, a575246ce0ba, já assumia essas
tabelas existentes: num banco vazio ela falhava com
`UndefinedTableError: relation "movimentacao" does not exist`, e não havia como
provisionar um ambiente novo a partir do repositório.

Esta migration preenche essa lacuna. Ela reconstrói o schema exatamente como
ele era ANTES de a575246ce0ba — ou seja, sem a tabela dispensacao, sem os
índices ix_alertas_* e com as FKs de alertas ainda sem ondelete, já que é a
a575246ce0ba que acrescenta essas três coisas. Assim a cadeia
`baseline -> a575246ce0ba` termina no mesmo schema que os models descrevem.

Bancos que já existiam (o Supabase de produção) estão gravados em
alembic_version como a575246ce0ba, que continua sendo o head da cadeia. Para
eles `alembic upgrade head` segue sendo um no-op: esta migration nunca roda, e
nada precisa ser feito manualmente.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2cf2197c6b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicamento',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome_generico', sa.String(length=255), nullable=False),
    sa.Column('nome_comercial', sa.String(length=255), nullable=True),
    sa.Column('forma_farmaceutica', sa.String(length=100), nullable=False),
    sa.Column('concentracao', sa.String(length=100), nullable=False),
    sa.Column('via_administracao', sa.String(length=100), nullable=False),
    sa.Column('fabricante', sa.String(length=200), nullable=True),
    sa.Column('cod_ggrem', sa.String(length=30), nullable=True),
    sa.Column('registro_anvisa', sa.String(length=30), nullable=True),
    sa.Column('codigo_barras', sa.String(length=30), nullable=True),
    sa.Column('classe_terapeutica', sa.String(length=120), nullable=True),
    sa.Column('tipo_produto', sa.String(length=30), nullable=True),
    sa.Column('tarja', sa.String(length=60), nullable=True),
    sa.Column('restricao_hospitalar', sa.Boolean(), nullable=False),
    sa.Column('indicacao_farmacia_popular', sa.String(length=60), nullable=True),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('medicamento_pkey')),
    sa.UniqueConstraint('cod_ggrem', name=op.f('medicamento_cod_ggrem_key'))
    )
    op.create_index(op.f('ix_medicamento_indicacao_farmacia_popular'), 'medicamento', ['indicacao_farmacia_popular'], unique=False)
    op.create_table('paciente',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=15), nullable=False),
    sa.Column('condicao_clinica', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('paciente_pkey')),
    sa.UniqueConstraint('codigo', name=op.f('paciente_codigo_key'))
    )
    op.create_index(op.f('ix_paciente_condicao_clinica'), 'paciente', ['condicao_clinica'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('ATENDENTE', 'FARMACEUTICO', 'GESTOR', name='perfil_usuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usuario_pkey'))
    )
    op.create_index(op.f('ix_usuario_login'), 'usuario', ['login'], unique=True)
    op.create_table('lote',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('medicamento_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('registrado_por', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('numero_lote', sa.String(length=60), nullable=False),
    sa.Column('fabricante', sa.String(length=200), nullable=True),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.Column('quantidade_inicial', sa.Integer(), nullable=False),
    sa.Column('quantidade_atual', sa.Integer(), nullable=False),
    sa.Column('entrada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamento.id'], name=op.f('lote_medicamento_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuario.id'], name=op.f('lote_registrado_por_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('lote_pkey'))
    )
    op.create_index(op.f('ix_lote_medicamento_id'), 'lote', ['medicamento_id'], unique=False)
    op.create_index(op.f('ix_lote_validade'), 'lote', ['validade'], unique=False)
    op.create_table('alertas',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lote_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('medicamento_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tipo_alerta', sa.Enum('ALERTA_30_DIAS', 'ALERTA_15_DIAS', 'ALERTA_7_DIAS', 'ALERTA_ESTOQUE_CRITICO', name='tipo_alerta'), nullable=False),
    sa.Column('status_alerta', sa.Enum('PENDENTE', 'EM_ANDAMENTO', 'RESOLVIDO', 'EXPIRADO', name='status_alerta'), nullable=False),
    sa.Column('gerado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolvido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], name=op.f('alertas_lote_id_fkey')),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamento.id'], name=op.f('alertas_medicamento_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alertas_pkey'))
    )
    op.create_table('movimentacao',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lote_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('usuario_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', 'PERDA', 'AJUSTE', name='tipo_movimentacao'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('justificativa', sa.String(length=255), nullable=True),
    sa.Column('ocorrido_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], name=op.f('movimentacao_lote_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('movimentacao_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('movimentacao_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacao')
    op.drop_table('alertas')
    op.drop_index(op.f('ix_lote_validade'), table_name='lote')
    op.drop_index(op.f('ix_lote_medicamento_id'), table_name='lote')
    op.drop_table('lote')
    op.drop_index(op.f('ix_usuario_login'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_paciente_condicao_clinica'), table_name='paciente')
    op.drop_table('paciente')
    op.drop_index(op.f('ix_medicamento_indicacao_farmacia_popular'), table_name='medicamento')
    op.drop_table('medicamento')
    # ### end Alembic commands ###

    # No PostgreSQL, op.create_table cria os tipos ENUM das colunas, mas
    # op.drop_table NÃO os remove. Sem esta limpeza, um downgrade seguido de
    # upgrade falha com "type <nome> already exists".
    for tipo_enum in (
        "tipo_movimentacao",
        "status_alerta",
        "tipo_alerta",
        "perfil_usuario",
    ):
        op.execute(f"DROP TYPE IF EXISTS {tipo_enum}")
